### ISSUE TITLE
[SCAN] sub-05_ses-001

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/ood.stimuli#1]
# general infos
#### Setup
check all the equipment that was set up

- [x]  biopac
- [x]  sensimetrics
- [x]  eyetracker

#### general notes

Participant's feet cold at the beginning of the session. We've added a blanket, but PPG amplitude small. Small ECG amplitude, RSP ok, EDA a bit noisy.

#### task-ood_run-chaplin1 completion

- [x]  series was completed.

#### task-ood_run-chaplin1 notes

> Eye-tracker
> Calibration ok
> 
> Physio
> ECG and PPG really noisy
> RSP ok
> EDA not fluctuating much
> Some motion artefacts

#### task-ood_run-chaplin2 completion

- [x]  series was completed.

#### task-ood_run-chaplin2 notes

> Eye-tracker
> Lots of Cs after validation. RA decided to continue anyway due to time constraints.
> 
> Physio
> Some motion artefacts
> Between runs: PPG waveform good
> During run: some fluctuations in the EDA signal

#### task-ood_run-mononoke1 completion

- [x]  series was completed.

#### task-ood_run-mononoke1 notes

> Eye-tracker
> Validation ok
> 
> Physio
> Same as previous run
> Some motion related artefacts in the signal

#### task-ood_run-mononoke2 completion

- [x]  series was completed.

#### task-ood_run-mononoke2 notes

> Eye-tracker
> Validation: good
> 
> Physio
> Same as previous run
