### ISSUE TITLE
[SCAN] sub-03_ses-001

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/ood.stimuli#2]
# general infos
#### Setup
check all the equipment that was set up

- [x]  biopac
- [x]  sensimetrics
- [x]  eyetracker

#### general notes

Noisy PPG signal during setup. ECG and RSP good, EDA ok (EDA gain set at 2).
**PPG signal just noise; won't be usable. Due to time constraints, RA didn't try to fix it.**

#### task-ood_run-chaplin1 completion

- [X]  series was completed.

#### task-ood_run-chaplin1 notes

> Eye-tracker
> Calibration good !
> 
> Physio
> PPG noisy, not able to see systolic peaks on the waveform
> ECG great, R peaks clean
> RSP good
> EDA not fluctuating much (amplitude around 5.10 microsiemens)

#### task-ood_run-chaplin2 completion

- [X]  series was completed.

#### task-ood_run-chaplin2 issues

- [X] physio quality issue

#### task-ood_run-chaplin2 notes

> Eye-tracker
>  Calibration good !
> 
> Physio
> Before the run: PPG and EDA signal noisy; ECG and RSP good
> During the run: Flat PPG waveform. ECG and RSP good. Some fluctuations in EDA signals.

#### task-ood_run-mononoke1 completion

- [X]  series was completed.

#### task-ood_run-mononoke1 issues

- [X] physio quality issue

#### task-ood_run-mononoke1 notes

> Eye-tracker
>  Calibration ok (lots of Bs for distance, due to time contraints, calibration was not run again)
> 
> Physio
>  PPG not usable (see General notes)
> ECG and RSP good
> EDA a bit noisy, but SCRs visible in the signal.

#### task-ood_run-mononoke2 completion

- [X]  series was completed.

#### task-ood_run-mononoke2 issues

- [X] physio quality issue

#### task-ood_run-mononoke2 notes

> Eye-tracker
>  Lots of Cs for distance... (due to time contraints, calibration was not run again)
> 
> Physio
>  PPG won't be usable (see General notes)
> ECG, RSP, EDA good

#### task-ood_run-passepartout1 completion

- [X]  series was completed.

#### task-ood_run-passepartout1 notes

> Eye-tracker
>  Lots of Bs for Distance after eyetracker validation 
> 
> Physio
>  Same as previous run

#### task-ood_run-passepartout2 completion

- [X]  series was completed.

#### task-ood_run-passepartout2 notes

> Eye-tracker
>  Calibration ok
> 
> Physio
>  PPG noisy
> ECG, RSP good. EDA a bit noisy but SCRs visible in the waveform
